# Generated by Django 4.2.2 on 2023-06-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('candiate_doj', models.DateField()),
                ('candiate_email_id', models.EmailField(max_length=50)),
                ('hiring_manager', models.CharField(max_length=100)),
                ('hiring_manager_email_id', models.EmailField(max_length=50)),
            ],
            options={
                'verbose_name': 'Candidate Details',
            },
        ),
    ]
