# Generated by Django 3.2.16 on 2023-06-13 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deni_apps', '0002_alter_candidatedetails_candiate_doj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCandidateDetails',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('candiate_doj', models.DateField(verbose_name='Candidate Joining Date')),
                ('candiate_email_id', models.EmailField(max_length=50, verbose_name='Candidate Email Id')),
                ('hiring_manager', models.CharField(max_length=100, verbose_name='Hiring Manager')),
                ('hiring_manager_email_id', models.EmailField(max_length=50, verbose_name='Hiring Manager Email Id')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Candidate Details',
                'verbose_name_plural': 'historical Candidate Detailss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
