# Generated by Django 3.2.16 on 2023-06-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deni_apps', '0003_historical_candidate_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatedetails',
            name='email_sent_date',
            field=models.DateField(default=None, verbose_name='Email Sent Date'),
        ),
        migrations.AddField(
            model_name='candidatedetails',
            name='offer_accepted_date',
            field=models.DateField(default=None, verbose_name='Offer Accepted Date'),
        ),
        migrations.DeleteModel(
            name='HistoricalCandidateDetails',
        ),
    ]
