# Generated by Django 3.2.16 on 2023-06-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deni_apps', '0005_auto_20230614_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatedetails',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
